module.exports = {
  getImageSource(imageName) {
    switch (imageName) {
      case "fahasaPromotion":
        return require("./abc.png");
      case "fahasaReload":
        return require("./fahasaReload.png");
      case "input":
        return require("./inputbook.png");
      case "move":
        return require("./move.png");
      case "shelf":
        return require("./shelf.png");
      case "block":
        return require("./processblock.png");
      case "cell":
        return require("./cellphone.png");
      case "setting":
        return require("./setting.png");
      case "pack":
        return require("./pack.png");
      case "tote":
        return require("./tote.png");
      case "noImage":
        return require("./no_image.png");
      case "printer":
        return require("./printer.png");
      case "wrap":
        return require("./wrap.png");
      case "tray":
        return require("./tray.png");
      case "log":
        return require("./log.png");
      case "user":
        return require("./user.png");
      case "SKU":
        return require("./SKU.png");
      case "inputDoc":
        return require("./inputDoc.png");
      case "timer":
        return require("./timer.png");
      case "giftbox":
        return require("./giftbox.png");
      case "reset":
        return require("./reset.png");
      case "docreport":
        return require("./docreport.png");
      case "plus":
        return require("./plus.png");
      case "checkout":
        return require("./checkout.png");
      case "ordermanager":
        return require("./ordermanager.png");
      case "search":
        return require("./search.png");
      case "trash":
        return require("./trash.png");
      case "truck":
        return require("./truck.png");
      case "invprocess":
        return require("./invprocess.png");
      case "invmanager":
        return require("./invmanager.png");
      case "delivery":
        return require("./delivery.png");
      case "deliveryM":
        return require("./deliveryM.png");
        case "pendingList":
        return require("./pendingList.png");
        case "newOrderList":
        return require("./newOrderList.png");
        case "ongoingOrderList":
        return require("./ongoingOrderList.png");
        case "deliveryHistory":
        return require("./deliveryHistory.png");
        case "scanFindOrder":
        return require("./scanFindOrder.png");
        case "deliveryManager":
        return require("./deliveryManager.png");
        case "receiveMoneyList":
            return require("./receiveMoneyList.png");
    }
  }
};
